-- AlterTable
ALTER TABLE "Class" ADD COLUMN "basicRules" BOOLEAN;
ALTER TABLE "Class" ADD COLUMN "basicRules2024" BOOLEAN;
ALTER TABLE "Class" ADD COLUMN "reprintedAs" JSONB;
ALTER TABLE "Class" ADD COLUMN "srd" BOOLEAN;
ALTER TABLE "Class" ADD COLUMN "srd52" BOOLEAN;
