-- AlterTable
ALTER TABLE "Class" ADD COLUMN "optionalfeatureProgression" JSONB;

-- CreateTable
CREATE TABLE "OptionalFeature" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "source" TEXT,
    "featureType" JSONB,
    "prerequisite" JSONB,
    "prerequisiteSummary" JSONB,
    "entries" JSONB,
    "entriesHigherLevel" JSONB,
    "additionalSpells" JSONB,
    "addSpells" JSONB,
    "removeSpells" JSONB,
    "gainSubclassFeature" JSONB,
    "gainAnotherFeature" JSONB,
    "otherSources" JSONB,
    "page" JSONB,
    "className" JSONB,
    "classSource" JSONB,
    "subclassName" JSONB,
    "subclassShortName" JSONB,
    "subclassSource" JSONB,
    "level" JSONB,
    "ability" JSONB,
    "savingThrowProficiencies" JSONB,
    "skillProficiencies" JSONB,
    "toolProficiencies" JSONB,
    "languageProficiencies" JSONB,
    "flags" JSONB,
    "repeatable" JSONB,
    "prerequisiteAbility" JSONB,
    "prerequisiteSpell" JSONB,
    "otherPrerequisites" JSONB,
    "fluff" JSONB,
    "hasFluff" JSONB,
    "hasFluffImages" JSONB,
    "srd" JSONB,
    "srd52" JSONB,
    "basicRules" JSONB,
    "data" JSONB
);
