/*
  Warnings:

  - You are about to alter the column `charges` on the `Item` table. The data in that column could be lost. The data in that column will be cast from `String` to `Json`.

*/
-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Item" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "page" INTEGER,
    "type" TEXT,
    "rarity" TEXT,
    "reqAttuneTags" JSONB,
    "wondrous" BOOLEAN,
    "bonusSpellAttack" TEXT,
    "bonusSpellSaveDc" TEXT,
    "focus" JSONB,
    "entries" JSONB,
    "hasFluffImages" BOOLEAN,
    "baseItem" TEXT,
    "weaponCategory" TEXT,
    "dmg1" TEXT,
    "dmg2" TEXT,
    "grantsProficiency" BOOLEAN,
    "additionalSources" JSONB,
    "additionalEntries" JSONB,
    "light" JSONB,
    "modifySpeed" JSONB,
    "group" JSONB,
    "scfType" TEXT,
    "curse" BOOLEAN,
    "ability" JSONB,
    "age" TEXT,
    "seeAlsoVehicle" JSONB,
    "range" TEXT,
    "strength" TEXT,
    "stealth" BOOLEAN,
    "immune" JSONB,
    "vulnerable" JSONB,
    "poison" BOOLEAN,
    "poisonTypes" JSONB,
    "mastery" JSONB,
    "containerCapacity" JSONB,
    "packContents" JSONB,
    "atomicPackContents" BOOLEAN,
    "otherSources" JSONB,
    "grantsLanguage" BOOLEAN,
    "staff" BOOLEAN,
    "bonusWeaponAttack" TEXT,
    "bonusWeaponDamage" TEXT,
    "critThreshold" INTEGER,
    "carryingCapacity" INTEGER,
    "speed" INTEGER,
    "ammoType" TEXT,
    "alias" JSONB,
    "seeAlsoDeck" JSONB,
    "valueRarity" TEXT,
    "spellScrollLevel" INTEGER,
    "hasFluff" BOOLEAN,
    "barDimensions" JSONB,
    "reqAttuneAlt" TEXT,
    "reach" INTEGER,
    "bonusProficiencyBonus" TEXT,
    "firearm" BOOLEAN,
    "bonusSavingThrowConcentration" TEXT,
    "typeAlt" TEXT,
    "detail2" TEXT,
    "dexterityMax" INTEGER,
    "crewMin" INTEGER,
    "crewMax" INTEGER,
    "travelCost" INTEGER,
    "shippingCost" INTEGER,
    "bonusAbilityCheck" TEXT,
    "sentient" BOOLEAN,
    "bonusWeapon" TEXT,
    "reprintedAs" JSONB,
    "tier" TEXT,
    "lootTables" JSONB,
    "srd" JSONB,
    "srd52" JSONB,
    "basicRules2024" BOOLEAN,
    "_copy" JSONB,
    "bonusAc" TEXT,
    "bonusSavingThrow" TEXT,
    "optionalfeatures" JSONB,
    "resist" JSONB,
    "basicRules" BOOLEAN,
    "recharge" TEXT,
    "rechargeAmount" JSONB,
    "charges" JSONB,
    "miscTags" JSONB,
    "detail1" TEXT,
    "tattoo" BOOLEAN,
    "hasRefs" BOOLEAN,
    "attachedSpells" JSONB,
    "crew" INTEGER,
    "vehAc" INTEGER,
    "vehHp" INTEGER,
    "vehDmgThresh" INTEGER,
    "vehSpeed" INTEGER,
    "capPassenger" INTEGER,
    "capCargo" INTEGER,
    "conditionImmune" JSONB,
    "weight" REAL,
    "value" INTEGER,
    "dmgType" TEXT,
    "ac" INTEGER,
    "property" JSONB,
    "reqAttune" TEXT,
    "source" TEXT
);
INSERT INTO "new_Item" ("_copy", "ability", "ac", "additionalEntries", "additionalSources", "age", "alias", "ammoType", "atomicPackContents", "attachedSpells", "barDimensions", "baseItem", "basicRules", "basicRules2024", "bonusAbilityCheck", "bonusAc", "bonusProficiencyBonus", "bonusSavingThrow", "bonusSavingThrowConcentration", "bonusSpellAttack", "bonusSpellSaveDc", "bonusWeapon", "bonusWeaponAttack", "bonusWeaponDamage", "capCargo", "capPassenger", "carryingCapacity", "charges", "conditionImmune", "containerCapacity", "crew", "crewMax", "crewMin", "critThreshold", "curse", "detail1", "detail2", "dexterityMax", "dmg1", "dmg2", "dmgType", "entries", "firearm", "focus", "grantsLanguage", "grantsProficiency", "group", "hasFluff", "hasFluffImages", "hasRefs", "id", "immune", "light", "lootTables", "mastery", "miscTags", "modifySpeed", "name", "optionalfeatures", "otherSources", "packContents", "page", "poison", "poisonTypes", "property", "range", "rarity", "reach", "recharge", "rechargeAmount", "reprintedAs", "reqAttune", "reqAttuneAlt", "reqAttuneTags", "resist", "scfType", "seeAlsoDeck", "seeAlsoVehicle", "sentient", "shippingCost", "source", "speed", "spellScrollLevel", "srd", "srd52", "staff", "stealth", "strength", "tattoo", "tier", "travelCost", "type", "typeAlt", "value", "valueRarity", "vehAc", "vehDmgThresh", "vehHp", "vehSpeed", "vulnerable", "weaponCategory", "weight", "wondrous") SELECT "_copy", "ability", "ac", "additionalEntries", "additionalSources", "age", "alias", "ammoType", "atomicPackContents", "attachedSpells", "barDimensions", "baseItem", "basicRules", "basicRules2024", "bonusAbilityCheck", "bonusAc", "bonusProficiencyBonus", "bonusSavingThrow", "bonusSavingThrowConcentration", "bonusSpellAttack", "bonusSpellSaveDc", "bonusWeapon", "bonusWeaponAttack", "bonusWeaponDamage", "capCargo", "capPassenger", "carryingCapacity", "charges", "conditionImmune", "containerCapacity", "crew", "crewMax", "crewMin", "critThreshold", "curse", "detail1", "detail2", "dexterityMax", "dmg1", "dmg2", "dmgType", "entries", "firearm", "focus", "grantsLanguage", "grantsProficiency", "group", "hasFluff", "hasFluffImages", "hasRefs", "id", "immune", "light", "lootTables", "mastery", "miscTags", "modifySpeed", "name", "optionalfeatures", "otherSources", "packContents", "page", "poison", "poisonTypes", "property", "range", "rarity", "reach", "recharge", "rechargeAmount", "reprintedAs", "reqAttune", "reqAttuneAlt", "reqAttuneTags", "resist", "scfType", "seeAlsoDeck", "seeAlsoVehicle", "sentient", "shippingCost", "source", "speed", "spellScrollLevel", "srd", "srd52", "staff", "stealth", "strength", "tattoo", "tier", "travelCost", "type", "typeAlt", "value", "valueRarity", "vehAc", "vehDmgThresh", "vehHp", "vehSpeed", "vulnerable", "weaponCategory", "weight", "wondrous" FROM "Item";
DROP TABLE "Item";
ALTER TABLE "new_Item" RENAME TO "Item";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
