-- AlterTable
ALTER TABLE "Feat" ADD COLUMN "basicRules" BOOLEAN;
ALTER TABLE "Feat" ADD COLUMN "basicRules2024" BOOLEAN;
ALTER TABLE "Feat" ADD COLUMN "category" TEXT;
ALTER TABLE "Feat" ADD COLUMN "repeatable" BOOLEAN;
ALTER TABLE "Feat" ADD COLUMN "repeatableHidden" BOOLEAN;
ALTER TABLE "Feat" ADD COLUMN "srd" BOOLEAN;
ALTER TABLE "Feat" ADD COLUMN "srd52" BOOLEAN;
